# Generated by Django 3.2.8 on 2022-03-24 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20220323_1414'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topics',
            options={'verbose_name': 'Тематика статьи', 'verbose_name_plural': 'Тематика статей'},
        ),
        migrations.AlterField(
            model_name='section',
            name='sname',
            field=models.CharField(max_length=30, verbose_name='Раздел'),
        ),
        migrations.AlterField(
            model_name='topics',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.section', verbose_name='Раздел'),
        ),
        migrations.AlterField(
            model_name='topics',
            name='main_section',
            field=models.BooleanField(),
        ),
    ]
