# Generated by Django 3.2.8 on 2022-03-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20220324_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topics',
            name='main_section',
            field=models.BooleanField(blank=True, verbose_name='Основной'),
        ),
    ]
