# Generated by Django 3.2.8 on 2022-03-24 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_topics_main_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topics',
            name='main_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Основной', to='articles.section'),
        ),
    ]
