# Generated by Django 3.2.8 on 2022-03-25 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_topics_main_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='sections',
            field=models.ManyToManyField(related_name='Sections', through='articles.Topics', to='articles.Article'),
        ),
        migrations.AlterField(
            model_name='topics',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article', verbose_name='Раздел'),
        ),
        migrations.AlterField(
            model_name='topics',
            name='main_section',
            field=models.BooleanField(blank=True, null=True, verbose_name='Основной'),
        ),
        migrations.AlterField(
            model_name='topics',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.section'),
        ),
    ]
