# Generated by Django 3.2.8 on 2022-03-25 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20220325_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='sections',
            field=models.ManyToManyField(through='articles.Topics', to='articles.Article'),
        ),
        migrations.AlterField(
            model_name='topics',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.section', verbose_name='Раздел'),
        ),
        migrations.AlterField(
            model_name='topics',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article'),
        ),
    ]
